### ISSUE TITLE
Error Running App

### ISSUE THREAD

**Issue by mmubasharsheikh** [Hamagistral/de-zoomcamp-ui#3]
I have been watching videos using this app and suddenly I got a white screen with an error in the middle. For reference, the screenshot is attached:

<img width="2024" alt="image" src="https://github.com/Hamagistral/de-zoomcamp-ui/assets/11888803/6776de17-86e5-45f5-9240-8cd802edc139">

I tried refreshing multiple times but the error is same.

FYI: I tried hard to refresh as well thinking something related to cache but still the same.

**Comment by Hamagistral** [comment]
Hello, it should be fixed now! Thank you for your help.
